name: deploy to itch
on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  ITCHIO_USERNAME: knexator
  ITCHIO_GAME: pipelines-learning
  BUTLER_API_KEY: ${{ secrets.BUTLER_API_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy
        run: butler push ./v1 $ITCHIO_USERNAME/$ITCHIO_GAME:html5
